### ISSUE TITLE
Remove me from your Contributors list

### ISSUE THREAD

**Issue by Zephyrkul** [ShitShowDevelopment/ShitShowCogs#1]
[I am not a contributor.](https://github.com/ShitShowDevelopment/ShitShowCogs/graphs/contributors)
I also do not endorse, sponsor, or even affiliate with this repository in any way.

**Comment by PhantomNimbi** [comment]
Sorry. That was an old link meant to serve as credit for the help you and many others had done with the old `logger` cog. 

I thought I removed that list when I dropped the `logger` cog. It's fixed now.
